# Generated by Django 6.0.1 on 2026-06-01 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=80)),
                ('servicios', models.CharField(max_length=200)),
                ('tiene_cabanas', models.BooleanField(default=False)),
                ('capacidad_cabanas', models.IntegerField(default=0)),
                ('capacidad_camping', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=50)),
                ('y', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('num_personas', models.PositiveSmallIntegerField(default=1)),
                ('tipo_visita', models.CharField(choices=[('CABANA', 'Cabaña'), ('CAMPING', 'Camping')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softbearApp.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
