# Generated by Django 6.0.1 on 2026-05-19 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=80)),
                ('x', models.IntegerField(default=50)),
                ('y', models.IntegerField(default=50)),
                ('servicios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('noches', models.PositiveSmallIntegerField(default=1)),
                ('personas', models.PositiveSmallIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('Cabaña', 'Cabaña'), ('Camping', 'Camping')], max_length=20)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softbearApp.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
