# Generated by Django 6.0.1 on 2026-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softbearApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='noches',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='personas',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='parque',
            name='capacidad_cabanas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parque',
            name='capacidad_camping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_cabanas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha_termino',
            field=models.DateField(default='2026-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='num_personas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='tipo_visita',
            field=models.CharField(choices=[('CABANA', 'Cabaña'), ('CAMPING', 'Camping')], default='CAMPING', max_length=10),
            preserve_default=False,
        ),
    ]
