# Generated by Django 6.0.1 on 2026-05-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softbearApp', '0002_remove_reservacion_noches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='x',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='y',
        ),
        migrations.AddField(
            model_name='parque',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parque',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
